// Generated by CoffeeScript 1.6.3
/*
 *		Holmes Core
 *
 *		@author Blackfish | Jesse Kivivuori
 *		@version 3.1.5
*/
(function() {
    var e, t, n = this;
    window.Holmes = {
        bookmarks: [],
        version: 3.17,
        showShortcutInfo: !1
    };
    t = function(e) {
        var n, r, i, s;
        s = [];
        for (r = 0, i = e.length; r < i; r++) {
            n = e[r];
            if (n.hasOwnProperty("children")) s.push(t(n.children));
            else if (!n.url.match(/^javascript/)) {
                n.title || (n.title = n.url);
                s.push(Holmes.bookmarks.push({
                    title: n.title,
                    url: n.url
                }))
            } else s.push(void 0)
        }
        return s
    };
    e = function() {
        return chrome.bookmarks.getTree(function(e) {
            Holmes.bookmarks = [];
            return t(e)
        })
    };
    chrome.bookmarks.onCreated.addListener(function(t, n) {
        return e()
    });
    chrome.bookmarks.onRemoved.addListener(function(t, n) {
        return e()
    });
    chrome.bookmarks.onChanged.addListener(function(t, n) {
        return e()
    });
    Holmes.getPlaceholder = function() {
        var e;
        e = ["Holmes at your service.", "How can I help you?", "It is a good day for searching.", "You know my methods. Apply them."];
        return e[Math.floor(Math.random() * e.length)]
    };
    e()
}).call(this);